version: '3.7'
services:
  pharmacyadmin:
    container_name: PharmacyADMIN
    restart: unless-stopped
    image: nerodacles/pharmacyadmin:latest
    build:
      context: ./
      target: dev
    networks:
      pharmacyapp:
        ipv4_address: 172.20.0.5
    volumes:
      - .:/src
    command: npm run serve
    ports:
      - "8088:3000"

networks:
  pharmacyapp:
    external: true