name: Docker Compose Actions Workflow
on:
  workflow_run:
    workflows: [Publish Docker image]
    types:
      - completed

jobs:
  DockerCompose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: npm install
        
      - name: Build the website
        run: npm run build
        
      - name: Build the stack
        run: docker-compose pull && docker-compose up -d --force-recreate
