name: Docker Compose Actions Workflow
on:
  workflow_run:
    workflows: [Publish Docker image]
    types:
      - completed

jobs:
  DockerCompose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: npm install
      - name: Build the website
        run: npm run build
      - name: Build the stack
        run: docker-compose pull && docker-compose up -d --force-recreate
        
  TestEndpoint:
    runs-on: ubuntu-latest
    needs: DockerCompose
    steps:
      - name: "Test API"
        uses: indiesdev/curl@v1.1
        with:
          url: "https://pharmacyadmin.jmcv.codes"
          method: "GET"
          accept: 200,201,204
          timeout: 2000
          log-response: true
          retries: 20